name: earnings-xgb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - sqlite
  - pip:
      - xgboost
      - shap